import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../global.css";
import { StoreProvider } from "@/store/StoreProvider";

import ClientProvider from "@/components/redux/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nixzobd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientProvider>
      <StoreProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </StoreProvider>
    </ClientProvider>
  );
}
