import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";
import ClientProvider from "@/components/redux/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nixzobd",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <ClientProvider>
    //   <StoreProvider>
    <html lang="en">
      <body>{children}</body>
    </html>
    //   </StoreProvider>
    // </ClientProvider>
  );
}
